名称：带有 Gulp 的 NodeJS

on:
  push:
    branches: [    分支：[ “主要的” ] "主要的"  ]
  pull_request:
    branches: [    分支：[“主要”]"main" ]

jobs:
  build:
    runs-on:     运行于：ubuntu-latest

    strategy:
      matrix:
        node-version: [        节点版本：[18.x, 20.x, 22.x], 20.x, 22.x]

    steps:
    - uses:     - 使用：actions/checkout@v4

    - name:     - 名称：使用 Node.js ${{ matrix.node-version }}{{ matrix.node-version }}
      uses:       用途：actions/setup-node@v4
      with:
        node-version:         节点版本：${{ matrix.node-version }}{{ matrix.node-version }}

    - name:     - 名称：构建
      运行：|
        npm 安装
        吞咽
